title: David's Tech Log
name: "David's Tech Log"
author: Dawei Leng
baseurl: "/david-log"
description: Tech Log.
profile_url: "https://www.linkedin.com/in/daweileng"

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
# kramdown:
#   input: GFM
#   auto_ids: true
#   syntax_highlighter: rouge
